"""Storage layer: the workspace registry, per-project networks, and the
generated read tiers (MAP.md, INVARIANTS.md, graph.json).

Read tiers, cheapest first:

  L0  MAP.md         one line per neuron - what the AI loads every session
  L1  neurons/*.md   the canonical fact in full - loaded on demand
  L2  evidence/      verbatim source material - loaded only when auditing

Nothing is ever deleted.  A fact that changes is superseded, never rewritten,
so the history stays reconstructable from the files alone.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import asdict
from datetime import date, datetime, timezone
from pathlib import Path

from . import schema
from .schema import Edge, Neuron

REGISTRY_VERSION = 1
GENERATED_BANNER = "<!-- generated by pcnn; edit neurons/, not this file -->"

#: neurons that must never be omitted from INVARIANTS.md
INVARIANT_LAYERS = ("CON", "DEC", "GOT")
INVARIANT_MIN_SALIENCE = 0.85


def today() -> str:
    return date.today().isoformat()


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def slug_to_scope(slug: str) -> str:
    """`yisoc-web` -> `YISOC_WEB`.  Must agree with schema.validate_neuron E006."""
    return re.sub(r"[^A-Za-z0-9_]", "_", slug).upper()


def home() -> Path:
    """The orchestrator root.  `PCNN_HOME` wins, else the package parent."""
    env = os.environ.get("PCNN_HOME")
    if env:
        return Path(env).resolve()
    return Path(__file__).resolve().parent.parent


# --------------------------------------------------------------------------
# Registry
# --------------------------------------------------------------------------

class Registry:
    """Maps a working directory to a project slug, and a slug to its network."""

    def __init__(self, root: Path | None = None) -> None:
        self.root = root or home()
        self.path = self.root / "registry.json"
        self.data: dict = {"version": REGISTRY_VERSION, "projects": {}}
        if self.path.exists():
            self.data = json.loads(self.path.read_text(encoding="utf-8"))
        self.data.setdefault("projects", {})

    # -- queries -----------------------------------------------------------
    @property
    def projects(self) -> dict[str, dict]:
        return self.data["projects"]

    def slugs(self) -> list[str]:
        return sorted(self.projects)

    def get(self, slug: str) -> dict | None:
        return self.projects.get(slug)

    def resolve_path(self, cwd: str | Path) -> str | None:
        """Longest-prefix match of `cwd` against registered project paths."""
        try:
            target = Path(cwd).resolve()
        except OSError:
            return None
        best, best_len = None, -1
        for slug, meta in self.projects.items():
            raw = meta.get("path")
            if not raw:
                continue
            try:
                base = Path(raw).resolve()
            except OSError:
                continue
            if target == base or base in target.parents:
                depth = len(base.parts)
                if depth > best_len:
                    best, best_len = slug, depth
        return best

    # -- mutation ----------------------------------------------------------
    def add(self, slug: str, path: str | Path, *, aliases: list[str] | None = None) -> dict:
        meta = self.projects.get(slug, {})
        meta.update({
            "scope": slug_to_scope(slug),
            "path": str(Path(path)),
            "aliases": aliases if aliases is not None else meta.get("aliases", []),
            "status": meta.get("status", "active"),
            "registered": meta.get("registered", today()),
        })
        self.projects[slug] = meta
        return meta

    def save(self) -> None:
        self.root.mkdir(parents=True, exist_ok=True)
        self.path.write_text(
            json.dumps(self.data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


# --------------------------------------------------------------------------
# Network
# --------------------------------------------------------------------------

class Network:
    """One project's neuron graph, backed by `networks/<slug>/`."""

    def __init__(self, slug: str, root: Path | None = None) -> None:
        self.slug = slug
        self.scope = slug_to_scope(slug)
        self.home = root or home()
        self.dir = self.home / "networks" / slug
        self.neurons: dict[str, Neuron] = {}
        self._loaded_text: dict[str, str] = {}

    # -- paths -------------------------------------------------------------
    @property
    def neuron_dir(self) -> Path:
        return self.dir / "neurons"

    @property
    def map_path(self) -> Path:
        return self.dir / "MAP.md"

    @property
    def invariants_path(self) -> Path:
        return self.dir / "INVARIANTS.md"

    @property
    def graph_path(self) -> Path:
        return self.dir / "graph.json"

    @property
    def changelog_path(self) -> Path:
        return self.dir / "CHANGELOG.ndjson"

    @property
    def recap_dir(self) -> Path:
        return self.dir / "recaps"

    @property
    def intake_dir(self) -> Path:
        return self.dir / "intake"

    @property
    def quarantine_dir(self) -> Path:
        return self.dir / "quarantine"

    def exists(self) -> bool:
        return self.dir.is_dir()

    # -- lifecycle ---------------------------------------------------------
    def init(self) -> None:
        for d in (self.neuron_dir, self.recap_dir, self.intake_dir, self.quarantine_dir):
            d.mkdir(parents=True, exist_ok=True)

    def load(self) -> "Network":
        self.neurons.clear()
        self._loaded_text.clear()
        if not self.neuron_dir.is_dir():
            return self
        for path in sorted(self.neuron_dir.glob("*.md")):
            text = path.read_text(encoding="utf-8")
            for n in schema.loads(text, source=str(path)):
                if n.id in self.neurons:
                    raise schema.DSLError(
                        f"{path}: neuron {n.id} already defined in another file")
                self.neurons[n.id] = n
                self._loaded_text[n.id] = text
        return self

    def sorted_neurons(self) -> list[Neuron]:
        def key(n: Neuron) -> tuple:
            layer_rank = schema.LAYER_ORDER.index(n.layer) if n.layer in schema.LAYERS else 99
            return (layer_rank, -n.salience, n.id)
        return sorted(self.neurons.values(), key=key)

    # -- ids ---------------------------------------------------------------
    def next_id(self, layer: str) -> str:
        """Allocate the next free id for a layer.  Ids are never reused."""
        highest = 0
        prefix = f"{self.scope}.{layer}-"
        for nid in self.neurons:
            if nid.startswith(prefix):
                try:
                    highest = max(highest, int(nid[len(prefix):]))
                except ValueError:
                    continue
        # retired ids stay reserved via the changelog
        for entry in self.read_changelog():
            nid = entry.get("neuron", "")
            if nid.startswith(prefix):
                try:
                    highest = max(highest, int(nid[len(prefix):]))
                except ValueError:
                    continue
        return f"{prefix}{highest + 1:03d}"

    # -- writing -----------------------------------------------------------
    def neuron_path(self, n: Neuron) -> Path:
        slug = re.sub(r"[^a-z0-9]+", "-", n.head.lower()).strip("-")[:48] or "neuron"
        return self.neuron_dir / f"{n.id}--{slug}.md"

    def put(self, n: Neuron) -> Neuron:
        """Insert or update a neuron and write its file, enforcing the floor."""
        n = n.canonical()
        floor = schema.LAYERS.get(n.layer, 0.0)
        if n.salience < floor:
            n.salience = floor
        if not n.first_seen:
            n.first_seen = today()
        if not n.last_touched:
            n.last_touched = today()
        # ids never change file identity, so drop any stale file for this id
        for old in self.neuron_dir.glob(f"{n.id}--*.md"):
            old.unlink()
        self.neuron_dir.mkdir(parents=True, exist_ok=True)
        self.neuron_path(n).write_text(schema.dump_neuron(n), encoding="utf-8")
        self.neurons[n.id] = n
        return n

    def link(self, src: str, dst: str, etype: str, weight: float) -> None:
        n = self.neurons[src]
        weight = min(weight, schema.WEAK_EDGE_MAX_WEIGHT) if etype in schema.WEAK_EDGE_TYPES \
            else weight
        kept = [e for e in n.edges if not (e.dst == dst and e.type == etype)]
        kept.append(Edge(src, dst, etype, round(weight, 2)))
        n.edges = kept
        self.put(n)

    def touch(self, nid: str, when: str | None = None) -> None:
        n = self.neurons[nid]
        n.last_touched = when or today()
        self.put(n)

    # -- changelog ---------------------------------------------------------
    def log(self, op: str, neuron: str, *, cause: str = "", detail: dict | None = None) -> None:
        entry = {
            "ts": now_iso(),
            "op": op,
            "neuron": neuron,
            "cause": cause,
            "detail": detail or {},
        }
        self.dir.mkdir(parents=True, exist_ok=True)
        with self.changelog_path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(entry, ensure_ascii=False) + "\n")

    def read_changelog(self) -> list[dict]:
        if not self.changelog_path.exists():
            return []
        out = []
        for line in self.changelog_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
        return out

    # -- generated read tiers ---------------------------------------------
    def _short(self, nid: str) -> str:
        return nid[len(self.scope) + 1:] if nid.startswith(self.scope + ".") else nid

    def map_md(self) -> str:
        items = self.sorted_neurons()
        active = [n for n in items if n.status == "active"]
        lines = [
            f"# MAP - {self.slug}",
            "",
            GENERATED_BANNER,
            "",
            "L0 index of the project context network. One line per neuron. Columns:",
            "`id | layer | salience | flags | head | outgoing edges | code anchors`.",
            "Edge codes: " + ", ".join(f"{v}={k}" for k, v in schema.EDGE_ABBR.items()) + ".",
            "Targets are written without the project scope prefix.",
            "Open `neurons/<id>--*.md` for the full fact, rationale and evidence.",
            f"Run `python -m pcnn query {self.slug} \"<question>\"` to retrieve by",
            "spreading activation instead of reading linearly.",
            "",
            f"neurons: {len(items)} | active: {len(active)} | "
            f"generated: {today()} | dsl: v{schema.DSL_VERSION}",
            "",
        ]

        pinned = [n for n in items if n.pin and n.status == "active"]
        if pinned:
            lines += ["## PINNED - never act against these", ""]
            lines += [self._map_line(n) for n in pinned]
            lines.append("")

        for layer in schema.LAYER_ORDER:
            group = [n for n in items if n.layer == layer and not (n.pin and n.status == "active")]
            if not group:
                continue
            lines += [f"## {layer} - {_LAYER_BLURB[layer]}", ""]
            lines += [self._map_line(n) for n in group]
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _map_line(self, n: Neuron) -> str:
        flags = []
        if n.pin:
            flags.append("pin")
        if n.status != "active":
            flags.append(n.status)
        if n.confidence != "verified":
            flags.append(n.confidence)
        edges = ",".join(f"{schema.EDGE_ABBR.get(e.type, e.type)}>{self._short(e.dst)}"
                         for e in n.edges) or "-"
        anchors = ";".join(n.anchors) or "-"
        return (f"{n.id} | {n.layer} | s{n.salience:.2f} | {','.join(flags) or '-'} | "
                f"{n.head} | {edges} | {anchors}")

    def invariants_md(self) -> str:
        """The never-forget set, rendered in full.  No cap, no truncation."""
        items = self.sorted_neurons()
        keep = [n for n in items
                if n.status == "active"
                and (n.pin or (n.layer in INVARIANT_LAYERS
                               and n.salience >= INVARIANT_MIN_SALIENCE))]
        retired = [n for n in items if n.status in ("superseded", "deprecated")]

        lines = [
            f"# INVARIANTS - {self.slug}",
            "",
            GENERATED_BANNER,
            "",
            "Every pinned neuron plus every CON/DEC/GOT neuron at salience >= "
            f"{INVARIANT_MIN_SALIENCE:.2f}, rendered in full.",
            "Contradicting any entry below requires saying so explicitly first.",
            "",
        ]
        for n in keep:
            lines += [f"## {n.id} - {n.head}", ""]
            lines.append(f"- layer: {n.layer} | salience: {n.salience:.2f} | "
                         f"confidence: {n.confidence} | since: {n.first_seen or '?'}")
            lines.append(f"- fact: {n.description}")
            if n.rationale:
                lines.append(f"- why: {n.rationale}")
            if n.alternatives_rejected:
                lines.append(f"- rejected: {n.alternatives_rejected}")
            if n.anchors:
                lines.append(f"- anchors: {', '.join(n.anchors)}")
            if n.edges:
                lines.append("- connected: " + ", ".join(
                    f"{e.type} {self._short(e.dst)}" for e in n.edges))
            lines.append("")

        if retired:
            lines += [
                "## RETIRED - do not reintroduce",
                "",
                "These were true once and are not any more. Listed so a later session does",
                "not rediscover and re-adopt an approach that was already abandoned.",
                "",
            ]
            for n in retired:
                sup = [m.id for m in items
                       for e in m.outgoing("supersedes") if e.dst == n.id]
                by = f" (superseded by {', '.join(sup)})" if sup else ""
                lines.append(f"- {n.id} [{n.status}] {n.head}{by}")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def graph_dict(self) -> dict:
        nodes = []
        edges = []
        for n in self.sorted_neurons():
            d = asdict(n)
            d.pop("line", None)
            d.pop("edges", None)
            d["floor"] = schema.LAYERS.get(n.layer, 0.0)
            nodes.append(d)
            for e in n.edges:
                edges.append({"src": e.src, "dst": e.dst, "type": e.type,
                              "weight": round(e.weight, 2)})
        return {
            "dsl": schema.DSL_VERSION,
            "project": self.slug,
            "scope": self.scope,
            "generated": now_iso(),
            "layers": schema.LAYERS,
            "edge_types": schema.EDGE_TYPES,
            "nodes": nodes,
            "edges": edges,
        }

    def rebuild(self) -> None:
        """Regenerate every derived file from `neurons/`.

        A caller that forgot to `load()` would otherwise write a map of whatever
        it happened to have in memory over a map of the whole network.  The
        neuron files are the source of truth, so if the directory holds more
        than this instance does, the directory wins and is re-read first.
        """
        if self.neuron_dir.is_dir():
            on_disk = len(list(self.neuron_dir.glob("*.md")))
            if on_disk > len(self.neurons):
                self.load()
        self.dir.mkdir(parents=True, exist_ok=True)
        self.map_path.write_text(self.map_md(), encoding="utf-8")
        self.invariants_path.write_text(self.invariants_md(), encoding="utf-8")
        self.graph_path.write_text(
            json.dumps(self.graph_dict(), indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8")

    # -- validation --------------------------------------------------------
    def validate(self) -> list[schema.Finding]:
        return schema.validate_graph(self.neurons.values())


_LAYER_BLURB = {
    "IDENT": "what the project is, goal, users, done-criteria",
    "DEC": "choices made, with rationale and rejected alternatives",
    "CON": "invariants: must and never rules, platform limits",
    "ARC": "components, boundaries, data flow",
    "IMP": "concrete modules and functions",
    "DAT": "schemas, API shapes, config keys, env vars, formats",
    "OPS": "run, build, deploy, ports, secrets, versions",
    "GOT": "what broke, why, the fix, what not to retry",
    "TODO": "open threads, unknowns, deferred work",
    "GLO": "domain terms and canonical naming",
    "PAT": "reusable cross-project patterns",
}


def load_all(root: Path | None = None) -> dict[str, Network]:
    """Load every registered network plus the cross-project scope."""
    reg = Registry(root)
    out: dict[str, Network] = {}
    for slug in reg.slugs():
        net = Network(slug, root)
        if net.exists():
            out[slug] = net.load()
    xprj = Network("xprj", root)
    if xprj.exists():
        out["xprj"] = xprj.load()
    return out
